name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      my_input:
        description: "A sample input"
        required: true
        type: string

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Input was ${{ github.event.inputs.my_input }}"
